n=bool(input('Enter your boolean number'))
print('the integer value of the number is :',int(n))
print('the float value of the number is :',float(n))
print('the string value of the number is :',str(n))
print('the complex value of the number is :',complex(n))
print('the hexadecimal value of the number is :',hex(n))
print('the octal value of the number is :',oct(n))
print('the binary value of the number is :',bin(n))
