i=int(input('Enter your integer number'))
print('hexadecimal value of the number is :', hex(i))
print('octal value of the number is :', oct(i))
print('binary value of the number is :', bin(i))
print('float value of the number is :', float(i))
print('complex value of the number is :', complex(i))
print('boolean value of the number is :', bool(i))
print('string value of the number is :', str(i))
